name: Build and Deploy
on:
  push:
    branches: [ "master" ]
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and deploy app
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0 ## replace by latest version without it you will see Expected format {org}/{repo}[/path]@ref. Actual 'AhsanAyaz/angular-deploy-gh-pages-actions',Input string was not in a correct format.
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          build_configuration: production
          base_href: https://antonlevchenko.github.io/task-manager/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/tasks-manager/browser

permissions:
  contents: write
